/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Adzan
 */
public class ViewRuangan extends javax.swing.JFrame {

    /**
     * Creates new form ViewRuangan
     */
    public ViewRuangan() {
        initComponents();
    }
    
    public JButton getBtnTambahRuangan() {
        return btnTambahRuangan;
    }
    
    public JButton getBtnCariRuangan(){
        return btnCariRuangan;
    }
    
    public JButton getBtnTambahPasienInap(){
        return btnTambahPasienInap;
    }
    
    public JButton getBtnCariPasienInapIndex(){
        return btnCariPasienInapIndex;
    }
    
    public JButton getBtnCariPasienInapId(){
        return btnCariPasienInapId;
    }
    
    public JButton getBtnLihatSemuaPasienInap(){
        return btnLihatSemuaPasienInap;
    }
    
    public JButton getBtnKembaliRuangan(){
        return btnKembaliRuangan;
    }
    
    public void addListener(ActionListener e){ 
        btnCariPasienInapId.addActionListener(e);
        btnCariPasienInapIndex.addActionListener(e);
        btnCariRuangan.addActionListener(e);
        btnKembaliRuangan.addActionListener(e);
        btnLihatSemuaPasienInap.addActionListener(e);
        btnTambahPasienInap.addActionListener(e);
        btnTambahRuangan.addActionListener(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnTambahRuangan = new javax.swing.JButton();
        btnCariRuangan = new javax.swing.JButton();
        btnTambahPasienInap = new javax.swing.JButton();
        btnCariPasienInapIndex = new javax.swing.JButton();
        btnCariPasienInapId = new javax.swing.JButton();
        btnLihatSemuaPasienInap = new javax.swing.JButton();
        btnKembaliRuangan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setText("Ruangan");

        jLabel2.setText("-----------------------------------------------------------------------------------------------");

        btnTambahRuangan.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnTambahRuangan.setText("Tambah Data Ruangan");

        btnCariRuangan.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnCariRuangan.setText("Cari Data Ruangan");

        btnTambahPasienInap.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnTambahPasienInap.setText("Tambah Data Pasien Inap");

        btnCariPasienInapIndex.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnCariPasienInapIndex.setText("Cari Data Pasien Inap (Index)");

        btnCariPasienInapId.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnCariPasienInapId.setText("Cari Data Pasien Inap (No. ID)");

        btnLihatSemuaPasienInap.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnLihatSemuaPasienInap.setText("Lihat Semua Pasien Inap");

        btnKembaliRuangan.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnKembaliRuangan.setText("Kembali");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnTambahRuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCariRuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnTambahPasienInap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCariPasienInapIndex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCariPasienInapId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLihatSemuaPasienInap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnKembaliRuangan)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTambahRuangan)
                .addGap(20, 20, 20)
                .addComponent(btnCariRuangan)
                .addGap(18, 18, 18)
                .addComponent(btnTambahPasienInap)
                .addGap(18, 18, 18)
                .addComponent(btnCariPasienInapIndex)
                .addGap(18, 18, 18)
                .addComponent(btnCariPasienInapId)
                .addGap(18, 18, 18)
                .addComponent(btnLihatSemuaPasienInap)
                .addGap(22, 22, 22)
                .addComponent(btnKembaliRuangan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRuangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariPasienInapId;
    private javax.swing.JButton btnCariPasienInapIndex;
    private javax.swing.JButton btnCariRuangan;
    private javax.swing.JButton btnKembaliRuangan;
    private javax.swing.JButton btnLihatSemuaPasienInap;
    private javax.swing.JButton btnTambahPasienInap;
    private javax.swing.JButton btnTambahRuangan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
